title = "Flat theme"
theme = "hugo-theme-flat"
themesDir = "../.."
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 4
baseURL = ""

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
mainSections = ['devlog','reviews']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true


# you can set multi row of footers like these

[[params.footer_rows]]
[[params.footer_rows.items]]
pre = """<a href="/">Home</a>"""

[[params.footer_rows]]
[[params.footer_rows.items]]
pre = """<a href="/frequently_asked_questions/">Contact & FAQ</a>"""

[[params.footer_rows]]
[[params.footer_rows.items]]
pre = """<a href="/index.xml">RSS Feed</a>"""






[[menus.main]]
pageref = "frequently_asked_questions"
name = "Contact & FAQ"
weight = 80

[[menus.main]]
pageref = "search"
name = "Search"
weight = 81


# Sub Menus
[[menus.main]]
name = "Category"
weight = 60

[[menus.main]]
parent = "Category"
name = "DevLog"
url = "/devlog/"
weight = 61

[[menus.main]]
parent = "Category"
name = "Reviews"
url = "/reviews/"
weight = 62
